[package]
name = "simple-ftp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
suppaftp = { version = "^6", features = ["native-tls", "secure"] }
native-tls = "0.2"
rand = "0.8"
sha2 = "0.10"
thiserror = "1.0"
hex = "0.4"
